paths:
  /api/products/:
    get:
      summary: Obtiene una lista de todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos de forma satisfactoria
          content:
            application/json:
              schemas:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "400":
          description: Hubo algun error por query mal generada
        "500":
          description: Hubo un error interno del servidor
    post:
      summary: Agrega un producto
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - in: body
          name: product
          description: Informacion necesaria para crear el producto
          schema:
            $ref: "#/definitions/Product"
      responses:
        "201":
          description: El producto fue creado correctamente
        "400":
          description: La solicitud de creacion no fue satisfactoria, usualmente por problemas de parametros
        "403":
          description: Hubo un error de autenticacion
        "500":
          description: Hubo un error interno del servidor
  /api/products/{id}:
    get:
      summary: Obtiene un solo producto
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: id del producto que se desea solicitar
          schema:
            $type: String
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: La solicitud no fue satisfactoria, usualmente por problemas de parametros
    put:
      summary: Edita un producto
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: id del producto que se desea editar
          schema:
            $type: String
        - in: body
          name: product
          description: Informacion necesaria para crear el producto
          schema:
            $ref: "#/definitions/Product"
      responses:
        "200":
          description: Respuesta con el producto editado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: La solicitud de edicion no fue satisfactoria, usualmente por problemas de parametros
        "403":
          description: Hubo un error de autenticacion
        "500":
          description: Hubo un error interno de servidor
    delete:
      summary: Permite eliminar un producto
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: id del produto que se desea eliminar
          schema:
            $type: String
      responses:
        "200":
          description: Respuesta con el producto eliminado
          cocntent:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: La solicitud de eliminacion no fue satisfactoria, usualmente por problemas de parametros
        "403":
          description: Hubo un error de autenticacion
        "500":
          description: Hubo un error interno del servidor

components:
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Product:
      type: object
      properties:
        id:
          type: ObjectId
          description: Id autogenerado por mongo
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        price:
          type: Number
          description: Precio del producto
        thumbnail:
          type: Array
          items:
            type: String
          description: Arreglo de urls con imagenes del producto
        code:
          type: String
          description: Codigo de producto
        stock:
          type: Number
          description: Cantidad de productos disponibles
        category:
          type: String
          description: Categoria del producto
        status:
          type: Boolean
          description: Disponibilidad del producto
      example:
        id: 645839f963zbc58233a53074
        title: Te de hierbas patagonicas
        description: Te verde de hierbas de jazmin cultivados en provincias patagonicas
        price: 1800
        thumbnail:
          [
            https://kikimarket.com.ar/wp-content/uploads/2021/04/te-verde-con-jazmin-x-20-saq-patagonia-kiki-market-tienda-natural-dietetica-herboristeria-villa-carlos-paz.jpg,
          ]
        code: asd123
        stock: 250
        category: Alimentos y Bebidas
        status: true

definitions:
  Product:
    type: object
    required:
      - title
      - description
      - price
      - thumbnail
      - code
      - stock
      - category
      - status
    properties:
      title:
        type: String
        description: Nombre del producto
      description:
        type: String
        description: Descripcion del producto
      price:
        type: Number
        description: Precio del producto
      thumbnail:
        type: Array
        items:
          type: String
        description: Arreglo de urls con imagenes del producto
      code:
        type: String
        description: Codigo de producto
      stock:
        type: Number
        description: Cantidad de productos disponibles
      category:
        type: String
        description: Categoria del producto
      status:
        type: Boolean
        description: Disponibilidad del producto
    example:
      title: Te de hierbas patagonicas
      description: Te verde de hierbas de jazmin cultivados en provincias patagonicas
      price: 1800
      thumbnail:
        [
          https://kikimarket.com.ar/wp-content/uploads/2021/04/te-verde-con-jazmin-x-20-saq-patagonia-kiki-market-tienda-natural-dietetica-herboristeria-villa-carlos-paz.jpg,
        ]
      code: asd123
      stock: 250
      category: Alimentos y Bebidas
      status: true
